version: "3.9"
services:
  runner:
    build: 
      context: .
      dockerfile: ./qa/runner/Dockerfile
    volumes:
      - ./qa/http_webrtc:/runner
      - ./qa/result:/result
      - ./qa/http_webrtc/webexec_conf:/webexec_config
    environment:
      PWARGS: ${PWARGS}
    depends_on:
      - terminal7
      - webexec
  terminal7:
    image: halverneus/static-file-server:latest
    environment:
      PORT: 80
    volumes:
      - ./dist:/web
  webexec:
    build:
      context: .
      dockerfile: ./qa/webexec/Dockerfile
    volumes:
      - ./qa/http_webrtc/webexec_conf:/home/webexec/.config/webexec
