name: Terminal7-Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --global yarn
      - run: yarn install --frozen-lockfile
        timout-minutes: 10
      - run: npm test
