name: Terminal7-Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: sudo apt-get update 
      - run: sudo apt-get install -y git chromium
      - run: yarn install --frozen-lockfile
      - run: npm test
