name: Terminal7-Tests

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --global yarn
      - run: yarn install --frozen-lockfile
  lint:
    needs: setup
    - run: yarn lint
  unit-test:
    needs: setup
    - run: yarn test
  atp:
    needs: setup
    - run: bash -x aatp/run
    - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: aatp-result
          path: aatp/result
